spring:
  datasource:
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  security:
    user:
      name: admin
      password: 123
server:
  port: 8999

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/yangpj/mapper/*.xml
